# Generated by Django 5.1.7 on 2025-11-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='storage_limit',
            field=models.PositiveIntegerField(default=5, help_text='Storage limit in GB'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='used_space',
            field=models.PositiveIntegerField(default=0, help_text='Used space in MB'),
        ),
    ]
