# Generated by Django 5.1.7 on 2025-11-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='podcast_details', serialize=False, to='movies.media')),
                ('host', models.CharField(max_length=255)),
                ('episode_count', models.PositiveIntegerField(default=1)),
                ('is_ongoing', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in MB', null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='copyright_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='media',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='media',
            name='used_space',
            field=models.PositiveIntegerField(default=0, help_text='Space used by this media in MB'),
        ),
        migrations.CreateModel(
            name='MediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.BooleanField(default=False)),
                ('upload_url', models.URLField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='movies.media')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.platform')),
            ],
        ),
    ]
