# Generated by Django 5.1.7 on 2025-11-18 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_platform_podcast_episode_file_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='short_video_details', serialize=False, to='movies.media')),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds, max 60')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='video_details', serialize=False, to='movies.media')),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
            ],
        ),
    ]
