# Generated by Django 5.1.7 on 2025-11-18 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_episode_description_alter_episode_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='simple_videos/')),
                ('title', models.CharField(blank=True, help_text='Extracted from file or user input', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, help_text='Extracted thumbnail', null=True, upload_to='simple_video_thumbnails/')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds, extracted from file', null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
