# Generated by Django 5.1.7 on 2025-11-19 06:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_video_media_video_created_at_video_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortvideo',
            name='media',
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Video height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Extracted thumbnail', null=True, upload_to='short_video_thumbnails/'),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='title',
            field=models.CharField(blank=True, help_text='Extracted from file or user input', max_length=255),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='short_videos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='video_file',
            field=models.FileField(default='file', upload_to='short_videos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Video width in pixels', null=True),
        ),
        migrations.AlterField(
            model_name='shortvideo',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds, max 180 (3 minutes)', null=True),
        ),
    ]
